Enforce nonconvex for OffsetConverter input instead of outputs
oemof/oemof-solph pull request #1068
Opened 2024-05-21 08:57 UTC by fwitte

Resolve #1067

2024-05-21 08:57 UTC, pep8speaks commented
Hello @fwitte! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`src/oemof/solph/components/_offset_converter.py`](https://github.com/oemof/oemof-solph/blob/bfc096bd3f26f97afc7e1e75ba77a54ce940b8f7/src/oemof/solph/components/_offset_converter.py):

> [Line 171:80](https://github.com/oemof/oemof-solph/blob/bfc096bd3f26f97afc7e1e75ba77a54ce940b8f7/src/oemof/solph/components/_offset_converter.py#L171): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)

2024-05-21 09:46 UTC, p-snft commented
Thank you. I think this issue came up as the offset is typically negative, so there would be no output without input. However, when taking into account the losses (as you did in #1067) you will always run into the issue. So, I'd also consider the current implementation broken.

As you suggested in the chat, it might make sense to change the keyword argument, when we change the implementation anyway. I'd suggest `conversion_factors` for the slope, as it's the same as for the (simple) `Converter`, and `normed_offset` to emphasise the fact that it's normed.

2024-05-21 09:51 UTC, fwitte commented
> Thank you. I think this issue came up as the offset is typically negative, so there would be no output without input. However, when taking into account the losses (as you did in #1067) you will always run into the issue. So, I'd also consider the current implementation broken.

Agree!

> As you suggested in the chat, it might make sense to change the keyword argument, when we change the implementation anyway. I'd suggest `conversion_factors` for the slope, as it's the same as for the (simple) `Converter`, and `normed_offset` to emphasise the fact that it's normed.

That sounds like a good idea. I will complete the changes in this PR then. This includes

- rename the keywords
- update the docs and examples
- fix/create tests

2024-05-21 09:57 UTC, fwitte commented
On top of that, I suggest a couple more changes:

- Rename to `MultiOutputOffsetConverter`, and we could add a new component called `MultiInputOffsetConverter` or
- enforce a single flow of all inputs and outputs to be `NonConvex`. This flow would be the basis for all other `conversion_factors` and `normed_offsets`. Therefore it also provides the `min` and `max` boundaries, as well as the `status_nominal` and also the `Invest` if it should be considered.

The second version would be more simple from the user perspective (you have to define a reference flow, i.e. the `NonConvex` one, and all given offsets and slopes refer to that, no matter if it has multi input, multi output or both, and no matter of that `NonConvex` flow is an input or an output. The other version is likely more easy to implement (or maintain), but I am not really sure. What do you think?

2024-05-21 11:52 UTC, fwitte commented
>     * enforce a single flow of all inputs and outputs to be `NonConvex`. This flow would be the basis for all other `conversion_factors` and `normed_offsets`. Therefore it also provides the `min` and `max` boundaries, as well as the `status_nominal` and also the `Invest` if it should be considered.

I drafted this version with my latest commit. I will readd the investment part after I have created two examples which we should discuss before putting more time into the changes.

2024-05-21 13:20 UTC, fwitte commented
## Example 1

electricity input with hydrogen (efficiency declining with load) and heat (efficiency increasing with load) output, reference is the only input flow:

![offset-two-output](https://github.com/oemof/oemof-solph/assets/20252362/8182144f-5051-4b81-863d-dea28b5fbb70)

```python
from oemof import solph
import numpy as np


t_steps = 11
es = solph.EnergySystem(timeindex=solph.create_time_index(year=2023, number=t_steps - 1))


eta_h2_min = 0.6
eta_h2_max = 0.5
P_in_min = 2
P_in_max = 10

P_out_min_h2 = P_in_min * eta_h2_min
P_out_max_h2 = P_in_max * eta_h2_max

slope_h2 = (P_out_max_h2 - P_out_min_h2) / (P_in_max - P_in_min)
offset_h2 = (P_out_max_h2 - slope_h2 * P_in_max) / P_in_max


eta_heat_min = 0.25
eta_heat_max = 0.3
P_out_min_heat = P_in_min * eta_heat_min
P_out_max_heat = P_in_max * eta_heat_max

slope_heat = (P_out_max_heat - P_out_min_heat) / (P_in_max - P_in_min)
offset_heat = (P_out_max_heat - slope_heat * P_in_max) / P_in_max



b_h2 = solph.Bus("hydrogen bus")
b_heat = solph.Bus("heat bus")
b_el = solph.Bus("electricity bus")

b_electrolyzer_h2 = solph.Bus("electrolyzer virtual input for h2")
b_electrolyzer_heat = solph.Bus("electrolyzer virtual input for heat")

source_el = solph.components.Source("electricity import", outputs={b_el: solph.Flow()})
sink_heat = solph.components.Sink("heat export", inputs={b_heat: solph.Flow()})
sink_h2 = solph.components.Sink("hydrogen export", inputs={b_h2: solph.Flow(fix=[0] + np.linspace(P_out_min_h2, P_out_max_h2, t_steps - 1).tolist(), nominal_value=1)})

electrolyzer = solph.components.OffsetConverter(
    label="electrolyzer",
    inputs={b_el: solph.Flow(nominal_value=P_in_max, nonconvex=solph.NonConvex(), min=P_in_min / P_in_max)},
    outputs={
        b_heat: solph.Flow(),
        b_h2: solph.Flow()
    },
    conversion_factors={
        b_heat: slope_heat,
        b_h2: slope_h2,
    },
    normed_offsets={b_heat: offset_heat, b_h2: offset_h2}
)

es.add(
    b_el, b_heat, b_h2,
    source_el, sink_h2, sink_heat,
    electrolyzer
)

om = solph.Model(es)

om.solve("gurobi")

result = solph.views.convert_keys_to_strings(om.results())
```

```python
heat = result[("electrolyzer", "heat bus")]["sequences"]["flow"]
el = result[("electricity bus", "electrolyzer")]["sequences"]["flow"]
h2 = result[("electrolyzer", "hydrogen bus")]["sequences"]["flow"]

plot_lines_and_conversion_efficiencies(
    {"flows": el, "min": P_in_min, "max": P_in_max, "commodity": "electricity input"},
    {"flows": heat, "offset": offset_heat, "slope": slope_heat, "commodity": "heat output"},
    {"flows": h2, "offset": offset_h2, "slope": slope_h2, "commodity": "h2 output"},
)
```

## Example 2

gas input and electricity output with electricity **(output commodity)** as reference, might not make that much sense, but to show, that it works.

![offset-single-output](https://github.com/oemof/oemof-solph/assets/20252362/971c869e-3388-449c-827d-733ab72fc9a8)

```python
from oemof import solph
import numpy as np


t_steps = 11
es = solph.EnergySystem(timeindex=solph.create_time_index(year=2023, number=t_steps - 1))


eta_el_min = 0.3
eta_el_max = 0.4
P_in_min = 2
P_in_max = 10

P_out_min_el = P_in_min * eta_el_min
P_out_max_el = P_in_max * eta_el_max

slope_gas = (P_in_max - P_in_min) / (P_out_max_el - P_out_min_el)
offset_gas = (P_in_max - slope_gas * P_out_max_el) / P_out_max_el


b_el = solph.Bus("electricity bus")
b_gas = solph.Bus("gas bus")

source_gas = solph.components.Source("gas import", outputs={b_gas: solph.Flow()})
sink_el = solph.components.Sink("electricity export", inputs={b_el: solph.Flow(fix=[0] + np.linspace(P_out_min_el, P_out_max_el, t_steps - 1).tolist(), nominal_value=1)})

chp = solph.components.OffsetConverter(
    label="chp",
    inputs={b_gas: solph.Flow()},
    outputs={
        b_el: solph.Flow(nominal_value=P_out_max_el, nonconvex=solph.NonConvex(), min=P_out_min_el / P_out_max_el)
    },
    conversion_factors={b_gas: slope_gas},
    normed_offsets={b_gas: offset_gas}
)

es.add(
    b_gas, b_el,
    source_gas, sink_el,
    chp
)

om = solph.Model(es)

om.solve("gurobi")

result = solph.views.convert_keys_to_strings(om.results())

el = result[("chp", "electricity bus")]["sequences"]["flow"]
gas = result[("gas bus", "chp")]["sequences"]["flow"]

plot_lines_and_conversion_efficiencies(
    {"flows": el, "min": P_out_min_el, "max": P_out_max_el, "commodity": "electricity output"},
    {"flows": gas, "offset": offset_gas, "slope": slope_gas, "commodity": "gas input"},
)
```

## Plotting code

```pythonimport matplotlib.pyplot as plt


def plot_lines_and_conversion_efficiencies(x, *args):

    fig, ax = plt.subplots(2, len(args), sharex=True)

    x_min = x["min"]
    x_max = x["max"]
    x_commodity = x["commodity"]
    x = x["flows"]

    ax = ax.transpose().flatten()

    for i, y in enumerate(args):
        offset = y["offset"]
        slope = y["slope"]
        y_commodity = y["commodity"]
        y = y["flows"]

        ax[2 * i].plot([0, x_min], [offset * x_max, offset * x_max + slope * x_min], "--", color="k")
        ax[2 * i].plot([x_min, x_max], [offset * x_max + slope * x_min, (offset + slope) * x_max], color="k")
        ax[2 * i].scatter(x, y)

        ax[2 * i].set_ylabel(y_commodity)
        ax[2 * i].grid()

        ax[2 * i + 1].scatter(x, y / x)
        ax[2 * i + 1].set_ylabel(f"{y_commodity} to {x_commodity} ratio")
        ax[2 * i + 1].grid()
        ax[2 * i + 1].set_xlabel(x_commodity)

    plt.tight_layout()
    fig.savefig("figure.png")
```

2024-05-28 10:00 UTC, fwitte commented
I added two "convenience functions", i.e. `calculate_slope_and_offset_with_reference_to_ouput` and `calculate_slope_and_offset_with_reference_to_input`. You provide the output/input nominal power, minimal power as well as the efficiencies at both points and it will give you the slope and the offset to describe those points. I think, it might be helpful for the users to have them available within `oemof-solph`. On the other hand, they somehow work like a preprocessing step for the `OffsetConverter`, therefore they could also be integrated as an own component masquerading/facading the `OffsetConverter` as alternative.

What do you think, is there a place for this kind of function inside `oemof-solph`?

2024-05-29 20:01 UTC, Bachibouzouk reviewed
Thanks @fwitte for this PR :) Nice work!

The review I made is not very in depth, I haven't tested it locally because of a lack of example I could readily run (i.e. lack of time to build such an example). However I still have a few suggestions that might be relevant:
- an example like https://github.com/oemof/oemof-solph/blob/dev/examples/offset_converter_example/offset_diesel_genset_nonconvex_investment.py would be nice
- what about the back compatibility? Shouldn't this component bear another name to avoid breaking changes? 
- an amendment to the documentation of the OffsetConverter would be good

2024-05-30 06:19 UTC, fwitte commented on docs/usage.rst
> +    >>> l_max = P_out_max/P_out_max  # upper part load limit
`l_max` in this case should actually be 1 (it was that way in the old version of the docs already, I did not change those lines except make them doc-testable). I think the only reasonable place for it not being 1, would be, if the min and max are time series or something like that. I could also remove that line and just pass 1 in the respective places...

What do you think?

2024-05-30 08:08 UTC, Bachibouzouk commented on docs/usage.rst
> +    >>> l_max = P_out_max/P_out_max  # upper part load limit
I think it is better to remain explicit then and thus not remove this line and simply set 1. I would be interested to know more about  the usecases where it is not 1

2024-05-30 10:36 UTC, fwitte commented on src/oemof/solph/components/_offset_converter.py
> +                msg = ""
This is the draft for the compatibility adapter to the old API of the `OffsetConverter`. I think I have to make two more changes (`FutureWarning`/`DepreciationWarning` to be added):

- the coefficients may be iterables, so I would have to calculate the slope and the offset correspondingly
- the max and min may also be iterables, if I see it correctly. What assumptions can be taken here: That the user specifies same length iterables for all of the attributes specified as iterables? May the usage crash without a proper message if he does not?

On top of that, are there more things to be taken into consideration?

Then, there is one last concern: The multi-output `OffsetConverter` made it to the `dev` branch very recently only. Can I consider that feature is not used by anyone yet and simply make it crash, e.g. in the case that users may have specified different `min` or `max` values for every output (which does not make sense, but was possible, see #1067)?

I will also add a test for this section in a different script...

2024-06-05 13:06 UTC, fwitte commented on src/oemof/solph/components/_offset_converter.py
> +):
done

2024-06-05 13:20 UTC, fwitte commented on docs/usage.rst
> +    ...     outputs={
Fixed

2024-06-05 13:29 UTC, p-snft commented on tests/constraint_tests.py
> +            solph.components._offset_converter.calculate_slope_and_offset_with_reference_to_output(
Independent from the complaint, you should not import from ` _{module}` . If the function is meant to be part of the public API, it should be in the `__init__`. Even if this already solves the line length complaint, you might want to give a shorter function name.

2024-06-05 13:49 UTC, fwitte commented on src/oemof/solph/components/_offset_converter.py
> +):
added as well

2024-06-06 11:00 UTC, fwitte commented
I added two more tests, one for double inputs and double outputs with the `NonConvex` flow at the input, and the same with the `NonConvex` flow at an output.

With that, I think this PR is ready for final review.

2024-06-06 14:32 UTC, p-snft requested changes
Thank you for this implementation. It really fills a gap. At the moment, there are few issues left to be fixed before merge.

2024-06-07 05:09 UTC, fwitte commented on docs/usage.rst
> +    ...     normed_offsets={bfuel: offset},
It is a diesel heat boiler, isn't it? The CHP could be in a different example.

2024-06-07 05:13 UTC, fwitte commented on src/oemof/solph/components/_offset_converter.py
> +        C_1 = \\frac{(l_{max}/\\eta_{max}-l_{min}/\\eta_{min}}{l_{max}-l_{min}}
Why b? In 5th grade (time runs fast, so might have been 10th grade also) mathematics class it was y=m*x + b for me.

2024-06-07 05:47 UTC, fwitte commented on src/oemof/solph/components/_offset_converter.py
> +        C_0 = \\frac{1}{\\eta_{max}} - C_1
I changed it together with the appearances in other places:

- C_1 -> m
- C_0 -> y_{0,normed}

2024-06-07 06:07 UTC, fwitte commented on tests/test_components.py
> +            conversion_factors={b_el: (2.5, 0.5)},
I updated all tests and test names, thank you.

2024-06-07 06:17 UTC, Bachibouzouk commented on src/oemof/solph/components/_offset_converter.py
> +        C_1 = \\frac{(l_{max}/\\eta_{max}-l_{min}/\\eta_{min}}{l_{max}-l_{min}}
Same for me, `m`is more intuitively a slope variable

2024-06-07 06:24 UTC, fwitte commented on tests/test_components/test_offset_converter.py
I added a test (2nd last in this file). It crashes in the `Flow.__init__` actually, before it even reaches the input output relation rules of the `OffsetConverterBlock`. Can we have a quick look together?

2024-06-07 08:12 UTC, fwitte commented on src/oemof/solph/components/_offset_converter.py
> +        C_1 = \\frac{(l_{max}/\\eta_{max}-l_{min}/\\eta_{min}}{l_{max}-l_{min}}
I went with `m` and `y_{0, normed}` (https://github.com/oemof/oemof-solph/pull/1068#discussion_r1630676746)

2024-06-07 13:24 UTC, fwitte commented on docs/usage.rst
> +    ...     normed_offsets={bfuel: offset},
Adjusted as well

2024-06-07 13:26 UTC, fwitte commented
@p-snft, I think, we are finally at it. I implemented a small plotting function for the new figures. I did not reference it anywhere in the docs. Although it is helpful, it could be refined a little bit maybe, I did not want to waste too much time on it.

Have a nice weekend!

2024-06-10 09:06 UTC, p-snft commented
The doc error reports that the linked page https://shop.vde.com/en/vde-study-the-cellular-approach has problems. This is no problem to be solved here. There is little to do, yet. I will contribute that myself.

2024-06-10 12:23 UTC, p-snft approved these changes
In my opinion, this is ready to be merged.

There are two remaining problems found by the automated process:
* Docs: Not all linked pages are available. (Not to be solved here.)
* Coverage: Test coverage decreases because of plotting functionality. As, however, this is not an advertised feature and nobody will rely on it, I think this is in order.

2024-06-19 07:16 UTC, merged